### ISSUE TITLE
[REQ] Add a (GH-compliant) license file

### ISSUE THREAD

**Issue by MarcoRavich** [LenzB1987/Lenz-disc-burn#1]
Hi there, 1st of all thanks for this cool work !

Since we've "doxed" it in our [HyMPS project](https://github.com/forart/HyMPS#readme) (under the [AUDIO category](https://github.com/forart/HyMPS#-) \ [Tools page](https://github.com/forart/HyMPS/blob/main/Audio/Tools.md#--) \ [Disc Tools subpage](https://github.com/forart/HyMPS/blob/main/Audio/DiscsTools.md#---) \ [Burning subsection](https://github.com/forart/HyMPS/blob/main/Audio/DiscsTools.md#burning-)), can you please add a license file for it ?

Although it may sounds like a minor aspect, license file uncompliance causes an inconsistent generation of the relative badge too:

![](https://flat.badgen.net/github/license/LenzB1987/Lenz-disc-burn/?label=LICENSE)
(badge-generator URL: https://flat.badgen.net/github/license/LenzB1987/Lenz-disc-burn/?label=LICENSE)

Anyway you can easily set a compliant one through the GH's license wizard tool.

Last but not least, let us know - in your opinion - how we could improve our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Thanks in advance.

**Comment by LenzB1987** [comment]
Ok I am going to add a license file

**Comment by LenzB1987** [comment]
Added a license file

**Comment by MarcoRavich** [comment]
Thanks !

Note that meanwhile we've changed files paths (fixed in the 1st message).
